### ISSUE TITLE
Tags should allow inner parenthesis

### ISSUE THREAD

**Issue by LetsZiggy** [edge-js/edge-sublime#4]
### Package version

2.1.2

### Describe the bug

![edge-syntax-before](https://github.com/edge-js/edge-sublime/assets/10394949/d6b82a38-522f-4835-a21a-9aeff0c3c0a4)

Tags able to have inner parenthesis without popping out of context on the first instance of closing parenthesis.

**Comment by thetutlage** [comment]
Fixed in https://github.com/edge-js/edge-sublime/commit/e8aacfbe69648b928b874494b967a641f299f8c5
